CREATE TABLE ACTOR (
    ID DECIMAL(12, 0) NOT NULL,
    NAME VARCHAR(30),
    SURNAME VARCHAR(30),
    INS_USERS DECIMAL(12, 0),
    MODIF_USERS DECIMAL(12, 0),
    DELETED SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY1 ON ACTOR (ID)CREATE TABLE ACTORS (
    ID DECIMAL(12, 0) NOT NULL,
    ID_MOVIE DECIMAL(12, 0),
    ID_ACTOR DECIMAL(12, 0),
    INS_USERS DECIMAL(12, 0),
    MODIF_USERS DECIMAL(12, 0),
    DELETED SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_ACTOR) REFERENCES ACTOR (ID),
    FOREIGN KEY (ID_MOVIE) REFERENCES MOVIE (ID)
);
CREATE UNIQUE INDEX RDB$FOREIGN27 ON ACTORS (ID_ACTOR);
CREATE UNIQUE INDEX RDB$FOREIGN28 ON ACTORS (ID_MOVIE);
CREATE UNIQUE INDEX RDB$PRIMARY2 ON ACTORS (ID)CREATE TABLE BORROW (
    ID DECIMAL(12, 0) NOT NULL,
    ID_DVD DECIMAL(12, 0) NOT NULL,
    ID_PERSON DECIMAL(12, 0) NOT NULL,
    DATE_BORROW DATE,
    DATE_RETURN DATE,
    INS_USERS DECIMAL(12, 0),
    MODIF_USERS DECIMAL(12, 0),
    DELETED SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_DVD) REFERENCES DVD (ID),
    FOREIGN KEY (ID_PERSON) REFERENCES PERSON (ID)
);
CREATE UNIQUE INDEX RDB$FOREIGN29 ON BORROW (ID_DVD);
CREATE UNIQUE INDEX RDB$FOREIGN30 ON BORROW (ID_PERSON);
CREATE UNIQUE INDEX RDB$PRIMARY3 ON BORROW (ID)CREATE TABLE DELETEDDVDNUMBER (
    ID DECIMAL(12, 0) NOT NULL,
    DVDNUMBER DECIMAL(12, 0) NOT NULL,
    PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$5 ON DELETEDDVDNUMBER (DVDNUMBER);
CREATE UNIQUE INDEX RDB$PRIMARY4 ON DELETEDDVDNUMBER (ID)CREATE TABLE DIRECTOR (
    ID DECIMAL(12, 0) NOT NULL,
    NAME VARCHAR(30),
    SURNAME VARCHAR(30),
    INS_USERS DECIMAL(12, 0),
    MODIF_USERS DECIMAL(12, 0),
    DELETED SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY6 ON DIRECTOR (ID)CREATE TABLE DIRECTORS (
    ID DECIMAL(12, 0) NOT NULL,
    ID_MOVIE DECIMAL(12, 0),
    ID_DIRECTOR DECIMAL(12, 0),
    INS_USERS DECIMAL(12, 0),
    MODIF_USERS DECIMAL(12, 0),
    DELETED SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_DIRECTOR) REFERENCES DIRECTOR (ID),
    FOREIGN KEY (ID_MOVIE) REFERENCES MOVIE (ID)
);
CREATE UNIQUE INDEX RDB$FOREIGN31 ON DIRECTORS (ID_DIRECTOR);
CREATE UNIQUE INDEX RDB$FOREIGN32 ON DIRECTORS (ID_MOVIE);
CREATE UNIQUE INDEX RDB$PRIMARY7 ON DIRECTORS (ID)CREATE TABLE DVD (
    ID DECIMAL(12, 0) NOT NULL,
    ID_MOVIE DECIMAL(12, 0) NOT NULL,
    NUMBER DECIMAL(12, 0),
    INS_USERS DECIMAL(12, 0),
    MODIF_USERS DECIMAL(12, 0),
    DELETED SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY8 ON DVD (ID)CREATE TABLE GROUP_RIGHTS (
    ID DECIMAL(12, 0) NOT NULL,
    ID_RIGHT DECIMAL(12, 0),
    ID_GROUP DECIMAL(12, 0),
    INS_USERS DECIMAL(12, 0),
    MODIF_USERS DECIMAL(12, 0),
    DELETED SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_GROUP) REFERENCES GROUPS (ID),
    FOREIGN KEY (ID_RIGHT) REFERENCES RIGHTS (ID)
);
CREATE UNIQUE INDEX RDB$FOREIGN33 ON GROUP_RIGHTS (ID_GROUP);
CREATE UNIQUE INDEX RDB$FOREIGN34 ON GROUP_RIGHTS (ID_RIGHT);
CREATE UNIQUE INDEX RDB$PRIMARY10 ON GROUP_RIGHTS (ID)CREATE TABLE GROUPS (
    ID DECIMAL(12, 0) NOT NULL,
    CODE VARCHAR(10),
    NAME VARCHAR(50),
    DESCRIPTION VARCHAR(200),
    INS_USERS DECIMAL(12, 0),
    MODIF_USERS DECIMAL(12, 0),
    DELETED SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY9 ON GROUPS (ID)CREATE TABLE HIST_DVD (
    ID DECIMAL(12, 0) NOT NULL,
    ID_DVD DECIMAL(12, 0) NOT NULL,
    ID_MOVIE DECIMAL(12, 0) NOT NULL,
    NUMBER DECIMAL(12, 0),
    INS_USERS DECIMAL(12, 0),
    MODIF_USERS DECIMAL(12, 0),
    DELETED SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY11 ON HIST_DVD (ID)CREATE TABLE HIST_MOVIE (
    ID DECIMAL(12, 0) NOT NULL,
    ID_MOVIE DECIMAL(12, 0) NOT NULL,
    CZECH_NAME VARCHAR(250),
    ORIG_NAME VARCHAR(250),
    GENRE DECIMAL(12, 0),
    DESCRIPTION VARCHAR(1024),
    COUNTRY DECIMAL(12, 0),
    IMAGE VARCHAR(250),
    LENGTH VARCHAR(5),
    "YEAR" VARCHAR(5),
    INS_USERS DECIMAL(12, 0),
    MODIF_USERS DECIMAL(12, 0),
    DELETED SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY12 ON HIST_MOVIE (ID)CREATE TABLE HIST_PARAMVARIABLE (
    ID DECIMAL(12, 0) NOT NULL,
    ID_PARAMVARIABLE DECIMAL(12, 0) NOT NULL,
    NAME_GROUP VARCHAR(20) NOT NULL,
    NAME_VAR VARCHAR(20) NOT NULL,
    C_VALUE VARCHAR(200),
    D_VALUE TIMESTAMP,
    N_VALUE DECIMAL(18, 6),
    VALID_FROM TIMESTAMP NOT NULL,
    VALID_TO TIMESTAMP,
    INS_USERS DECIMAL(12, 0),
    MODIF_USERS DECIMAL(12, 0),
    DELETED SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY13 ON HIST_PARAMVARIABLE (ID)CREATE TABLE "LANGUAGE" (
    ID DECIMAL(12, 0) NOT NULL,
    CODE VARCHAR(5),
    NAME VARCHAR(25),
    INS_USERS DECIMAL(12, 0),
    MODIF_USERS DECIMAL(12, 0),
    DELETED SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY14 ON "LANGUAGE" (ID)CREATE TABLE LANGUAGES (
    ID DECIMAL(12, 0) NOT NULL,
    ID_MOVIE DECIMAL(12, 0),
    ID_LANGUAGE DECIMAL(12, 0),
    INS_USERS DECIMAL(12, 0),
    MODIF_USERS DECIMAL(12, 0),
    DELETED SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_LANGUAGE) REFERENCES "LANGUAGE" (ID),
    FOREIGN KEY (ID_MOVIE) REFERENCES MOVIE (ID)
);
CREATE UNIQUE INDEX RDB$FOREIGN35 ON LANGUAGES (ID_LANGUAGE);
CREATE UNIQUE INDEX RDB$FOREIGN36 ON LANGUAGES (ID_MOVIE);
CREATE UNIQUE INDEX RDB$PRIMARY15 ON LANGUAGES (ID)CREATE TABLE MOVIE (
    ID DECIMAL(12, 0) NOT NULL,
    CZECH_NAME VARCHAR(250),
    ORIG_NAME VARCHAR(250),
    GENRE DECIMAL(12, 0),
    DESCRIPTION VARCHAR(4096),
    COUNTRY DECIMAL(12, 0),
    IMAGE VARCHAR(250),
    LENGTH VARCHAR(5),
    "YEAR" VARCHAR(5),
    INS_USERS DECIMAL(12, 0),
    MODIF_USERS DECIMAL(12, 0),
    DELETED SMALLINT NOT NULL DEFAULT 0,
    CSFD VARCHAR(1024),
    IMDB VARCHAR(1024),
    PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY16 ON MOVIE (ID)CREATE TABLE PARAMVARIABLE (
    ID DECIMAL(12, 0) NOT NULL,
    NAME_GROUP VARCHAR(20) NOT NULL,
    NAME_VAR VARCHAR(20) NOT NULL,
    C_VALUE VARCHAR(200),
    D_VALUE TIMESTAMP,
    N_VALUE DECIMAL(18, 6),
    VALID_FROM TIMESTAMP NOT NULL,
    VALID_TO TIMESTAMP,
    INS_USERS DECIMAL(12, 0),
    MODIF_USERS DECIMAL(12, 0),
    DELETED SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY17 ON PARAMVARIABLE (ID)CREATE TABLE PERSON (
    ID DECIMAL(12, 0) NOT NULL,
    NAME VARCHAR(30),
    SURNAME VARCHAR(30),
    MOBIL VARCHAR(20),
    PHONE VARCHAR(20),
    EMAIL VARCHAR(150),
    STREET VARCHAR(50),
    STREET_NUM VARCHAR(10),
    CITY VARCHAR(30),
    COUNTRY VARCHAR(30),
    INS_USERS DECIMAL(12, 0),
    MODIF_USERS DECIMAL(12, 0),
    DELETED SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY18 ON PERSON (ID)CREATE TABLE REGISTER (
    ID DECIMAL(12, 0) NOT NULL,
    CODE VARCHAR(10),
    NAME VARCHAR(50),
    DESCRIPTION VARCHAR(200),
    INS_USERS DECIMAL(12, 0),
    MODIF_USERS DECIMAL(12, 0),
    DELETED SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY19 ON REGISTER (ID)CREATE TABLE REGISTER_ITEM (
    ID DECIMAL(12, 0) NOT NULL,
    ID_REGISTER DECIMAL(12, 0),
    CODE VARCHAR(10),
    NAME VARCHAR(50),
    DESCRIPTION VARCHAR(200),
    INS_USERS DECIMAL(12, 0),
    MODIF_USERS DECIMAL(12, 0),
    DELETED SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_REGISTER) REFERENCES REGISTER (ID)
);
CREATE UNIQUE INDEX RDB$FOREIGN37 ON REGISTER_ITEM (ID_REGISTER);
CREATE UNIQUE INDEX RDB$PRIMARY20 ON REGISTER_ITEM (ID)CREATE TABLE RESERVATION (
    ID DECIMAL(12, 0) NOT NULL,
    ID_DVD DECIMAL(12, 0),
    ID_PERSON DECIMAL(12, 0),
    DATE_RESERVATION DATE,
    ID_BORROW DECIMAL(12, 0),
    DATE_BORROW DATE,
    INS_USERS DECIMAL(12, 0),
    MODIF_USERS DECIMAL(12, 0),
    DELETED SMALLINT,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_DVD) REFERENCES DVD (ID),
    FOREIGN KEY (ID_PERSON) REFERENCES PERSON (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY21 ON RESERVATION (ID)CREATE TABLE RIGHTS (
    ID DECIMAL(12, 0) NOT NULL,
    CODE VARCHAR(10),
    NAME VARCHAR(50),
    DESCRIPTION VARCHAR(200),
    INS_USERS DECIMAL(12, 0),
    MODIF_USERS DECIMAL(12, 0),
    DELETED SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY22 ON RIGHTS (ID)CREATE TABLE SUBSTITLE (
    ID DECIMAL(12, 0) NOT NULL,
    CODE VARCHAR(5),
    NAME VARCHAR(25),
    INS_USERS DECIMAL(12, 0),
    MODIF_USERS DECIMAL(12, 0),
    DELETED SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY23 ON SUBSTITLE (ID)CREATE TABLE SUBSTITLES (
    ID DECIMAL(12, 0) NOT NULL,
    ID_MOVIE DECIMAL(12, 0),
    ID_SUBSTITLE DECIMAL(12, 0),
    INS_USERS DECIMAL(12, 0),
    MODIF_USERS DECIMAL(12, 0),
    DELETED SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_MOVIE) REFERENCES MOVIE (ID),
    FOREIGN KEY (ID_SUBSTITLE) REFERENCES SUBSTITLE (ID)
);
CREATE UNIQUE INDEX RDB$FOREIGN38 ON SUBSTITLES (ID_MOVIE);
CREATE UNIQUE INDEX RDB$FOREIGN39 ON SUBSTITLES (ID_SUBSTITLE);
CREATE UNIQUE INDEX RDB$PRIMARY24 ON SUBSTITLES (ID)CREATE TABLE USERS (
    ID DECIMAL(12, 0) NOT NULL,
    ID_PERSON DECIMAL(12, 0),
    USERNAME VARCHAR(20) NOT NULL,
    PASS VARCHAR(50) NOT NULL,
    INS_USERS DECIMAL(12, 0),
    MODIF_USERS DECIMAL(12, 0),
    DELETED SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY25 ON USERS (ID)CREATE TABLE USERS_GROUP (
    ID DECIMAL(12, 0) NOT NULL,
    ID_USERS DECIMAL(12, 0),
    ID_GROUP DECIMAL(12, 0),
    INS_USERS DECIMAL(12, 0),
    MODIF_USERS DECIMAL(12, 0),
    DELETED SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_GROUP) REFERENCES GROUPS (ID),
    FOREIGN KEY (ID_USERS) REFERENCES USERS (ID)
);
CREATE UNIQUE INDEX RDB$FOREIGN40 ON USERS_GROUP (ID_USERS);
CREATE UNIQUE INDEX RDB$FOREIGN41 ON USERS_GROUP (ID_GROUP);
CREATE UNIQUE INDEX RDB$PRIMARY26 ON USERS_GROUP (ID);
