INSERT INTO GROUPS (ID, CODE, NAME, DESCRIPTION, INS_USERS, MODIF_USERS, DELETED) VALUES (2, 'SUPBIGADM', 'SUPERBIGADMIN', 'ALL RIGHTS', 1, 1, 0);
INSERT INTO GROUPS (ID, CODE, NAME, DESCRIPTION, INS_USERS, MODIF_USERS, DELETED) VALUES (3, 'USER', 'USERS', 'BFU', 1, 1, 0);
