INSERT INTO GROUP_RIGHTS (ID, ID_RIGHT, ID_GROUP, INS_USERS, MODIF_USERS, DELETED) VALUES (3, 1, 2, 1, 1, 0);
INSERT INTO GROUP_RIGHTS (ID, ID_RIGHT, ID_GROUP, INS_USERS, MODIF_USERS, DELETED) VALUES (4, 2, 2, 1, 1, 0);
INSERT INTO GROUP_RIGHTS (ID, ID_RIGHT, ID_GROUP, INS_USERS, MODIF_USERS, DELETED) VALUES (5, 3, 2, 1, 1, 0);
INSERT INTO GROUP_RIGHTS (ID, ID_RIGHT, ID_GROUP, INS_USERS, MODIF_USERS, DELETED) VALUES (6, 4, 2, 1, 1, 0);
INSERT INTO GROUP_RIGHTS (ID, ID_RIGHT, ID_GROUP, INS_USERS, MODIF_USERS, DELETED) VALUES (7, 5, 2, 1, 1, 0);
INSERT INTO GROUP_RIGHTS (ID, ID_RIGHT, ID_GROUP, INS_USERS, MODIF_USERS, DELETED) VALUES (8, 6, 2, 1, 1, 0);
INSERT INTO GROUP_RIGHTS (ID, ID_RIGHT, ID_GROUP, INS_USERS, MODIF_USERS, DELETED) VALUES (9, 7, 2, 1, 1, 0);
