INSERT INTO REGISTER (ID, CODE, NAME, DESCRIPTION, INS_USERS, MODIF_USERS, DELETED) VALUES (1, 'GENRE', 'Žánr', 'Žánr filmu', 1, 1, 0);
INSERT INTO REGISTER (ID, CODE, NAME, DESCRIPTION, INS_USERS, MODIF_USERS, DELETED) VALUES (2, 'COUNTRY', 'Zeme', 'stat', 1, 1, 0);
