INSERT INTO RIGHTS (ID, CODE, NAME, DESCRIPTION, INS_USERS, MODIF_USERS, DELETED) VALUES (1, 'MOVIEADD', 'ADD/EDIT movie', 'ADD/EDIT movie', 1, 1, 0);
INSERT INTO RIGHTS (ID, CODE, NAME, DESCRIPTION, INS_USERS, MODIF_USERS, DELETED) VALUES (2, 'MOVIEDEL', 'DEL movie', 'DELL movie', 1, 1, 0);
INSERT INTO RIGHTS (ID, CODE, NAME, DESCRIPTION, INS_USERS, MODIF_USERS, DELETED) VALUES (3, 'PERSADD', 'ADD/EDIT person', 'ADD/EDIT person', 1, 1, 0);
INSERT INTO RIGHTS (ID, CODE, NAME, DESCRIPTION, INS_USERS, MODIF_USERS, DELETED) VALUES (4, 'PERSLIST', 'LIST PERSON', 'LIST PERSON', 1, 1, 0);
INSERT INTO RIGHTS (ID, CODE, NAME, DESCRIPTION, INS_USERS, MODIF_USERS, DELETED) VALUES (5, 'PERSDELL', 'DEL person', 'DEL person', 1, 1, 0);
INSERT INTO RIGHTS (ID, CODE, NAME, DESCRIPTION, INS_USERS, MODIF_USERS, DELETED) VALUES (6, 'ADMIN', 'administrace', 'administrace', 1, 1, 0);
INSERT INTO RIGHTS (ID, CODE, NAME, DESCRIPTION, INS_USERS, MODIF_USERS, DELETED) VALUES (7, 'BORMOVIE', 'BORROW movie', 'pravo pujcovat filmy', 1, 1, 0);
