INSERT INTO USERS_GROUP (ID, ID_USERS, ID_GROUP, INS_USERS, MODIF_USERS, DELETED) VALUES (1, 1, 2, 1, 1, 0);
INSERT INTO USERS_GROUP (ID, ID_USERS, ID_GROUP, INS_USERS, MODIF_USERS, DELETED) VALUES (2, 3, 3, 1, 1, 0);
INSERT INTO USERS_GROUP (ID, ID_USERS, ID_GROUP, INS_USERS, MODIF_USERS, DELETED) VALUES (3, 2, 3, 1, 1, 0);
